#!/usr/bin/env bash

echo -n "GraphPlot[{"

temp_dir="$(mktemp -d)"
uc="$(mktemp)"

[[ ! -z $1 ]] && gs="$(jq '.[] .peer_id' < cache/$1.txt.json)"

for group in cache/*.json
do
	gname="${group%.txt.json}"
	gname="${gname##*/}"

	infos="$(jq '.[] .print_name, .[] .peer_id' < "$group" 2> /dev/null)" || continue

	_c_infos="$(($(wc -l <<< "$infos")/2))"
	count=$_c_infos
	head -n$_c_infos <<< "$infos" | while read -r uname
	do
		mapfile -s$count -n1 uid <<< "$infos"
		let count++
		[[ ! -z $1 ]] && {
			[[ $uid == $2 ]] && continue
			[[ $gs == *"$uid"* ]] || continue
		}
		echo "$uname -> \"$gname\", " >> $temp_dir/$uid
		echo "$uid" >> $uc
	done

done

for f in $(sort $uc | uniq -d)
do
	cat $temp_dir/$f
done | tr -d '\n' | sed -e 's/, $//;'

echo -n "}, VertexLabeling -> True]"
rm -r $temp_dir

